# Originally generated by nixos-generate-config, but hand-maintained
# since: see the note on fileSystems."/" below. Regenerating this file
# wholesale will reintroduce the boot hang, so merge changes in by hand.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/2c3b306e-1022-4a01-9647-25af6ce6dba3";

  # This must name the mapper device, not the ext4 filesystem's
  # /dev/disk/by-uuid/... path, because the systemd stage 1 initrd is
  # now the NixOS default.
  #
  # With a by-uuid path, systemd synthesises a .device unit for it and
  # applies DefaultDeviceTimeout (90s). That timer starts when the
  # initrd reaches initrd-root-device.target, which is *in parallel*
  # with the LUKS passphrase prompt -- so taking longer than 90s to
  # type the passphrase drops the machine into emergency mode.
  #
  # Naming /dev/mapper/cryptroot instead makes the generated mount unit
  # order itself after systemd-cryptsetup@cryptroot.service, which has
  # no such timeout, so the prompt waits indefinitely.
  fileSystems."/" =
    {
      device = "/dev/mapper/cryptroot";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/190E-029F";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/337de752-315a-4b28-b6e4-9f39bb2c1072"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
