# Originally generated by nixos-generate-config, but hand-maintained
# since: see the note on fileSystems."/" below. Regenerating this file
# wholesale will reintroduce the boot hang, so merge changes in by hand.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/2c3b306e-1022-4a01-9647-25af6ce6dba3";

  # This must name the mapper device, not the ext4 filesystem's
  # /dev/disk/by-uuid/... path, because the systemd stage 1 initrd is
  # now the NixOS default.
  #
  # With a by-uuid path, systemd synthesises a .device unit for it and
  # applies DefaultDeviceTimeout (90s). That timer starts when the
  # initrd reaches initrd-root-device.target, which is *in parallel*
  # with the LUKS passphrase prompt -- so taking longer than 90s to
  # type the passphrase drops the machine into emergency mode.
  #
  # Naming /dev/mapper/cryptroot instead makes the generated mount unit
  # order itself after systemd-cryptsetup@cryptroot.service, which has
  # no such timeout, so the prompt waits indefinitely.
  fileSystems."/" =
    {
      device = "/dev/mapper/cryptroot";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/190E-029F";
      fsType = "vfat";
    };

  # Swap sits in its own partition outside the LUKS container, so without
  # this anything paged out -- keys, buffers, documents -- would be readable
  # from the powered-off disk despite the encrypted root. randomEncryption
  # re-keys it from /dev/urandom on every boot, so nothing survives one.
  #
  # The device must be named by-partuuid, not by-uuid: re-keying re-runs
  # mkswap, which erases the swap signature and with it the by-uuid name.
  # NixOS asserts on that combination rather than letting it fail silently.
  #
  # The cost is hibernation, which cannot work with a key that is discarded
  # at power-off. Nothing here used it: there is no resume= on the kernel
  # command line, boot.resumeDevice is unset, and 8 GiB could not hold an
  # image of 31 GiB of RAM in any case.
  swapDevices =
    [{
      device = "/dev/disk/by-partuuid/214a77eb-7527-4295-b659-5416f5bfb924";
      randomEncryption.enable = true;
    }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
